# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: RangerZhou
subtitle: Read the fucking source code
description: 我是一个小流氓我从来也不浪，有一天我心血来潮耍了个流氓，我嘴里吹着小口哨我心里好得意，不知怎么哗啦啦啦啦我摔了一身泥
author: Ranger Zhou
email: ranger.assist@gmail.com
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://rangerzhou.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - 404.html
  - google42f54991665ae596.html
  - baidu_verify_vr4n4JeXgB.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
# https://hexo.io/docs/configuration#Date-Time-format
updated_option: mtime # 标题下显示更新于某某时间
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# SSH: git@github.com:rangerzhou/rangerzhou.github.io.git
# HTTPS: https://github.com/rangerzhou/rangerzhou.github.io.git
deploy:
  type: git
  repo: https://github.com/rangerzhou/rangerzhou.github.io.git
  branch: master

# Security
## https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md
## npm install --save hexo-blog-encrypt
encrypt:
    enable: true
    # 以下修改默认的提示和摘要内容
    # The content has been encrypted, enter the password to read.
    # Please enter the password to read.
    default_abstract: 加密文章，输入密码阅读</br>
    default_message: 请输入密码
    default_template:
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <div id="hbe-security">
          <div class="hbe-input-container">
          <input type="password" class="hbe-form-control" id="pass" placeholder="{{message}}" />
            <label for="pass">{{message}}</label>
            <div class="bottom-line"></div>
          </div>
        </div>
        <div id="decryptionError" style="display:none;">{{decryptionError}}</div>
        <div id="noContentError" style="display:none;">{{noContentError}}</div>
        <div id="encrypt-blog" style="display:none">
        {{content}}
        </div>

# Live2D 右下角动画
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-haru
  display:
    position: left
    width: 300
    height: 800
  mobile:
    show: false

aplayer:
  meting: true       # MetingJS 支持
#  cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js  # 引用 APlayer.js 外部 CDN 地址 (默认不开启)
#  style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
#  meting_cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js # 引用 Meting.js 外部 CDN 地址 (默认不开启)
